const STORAGE_KEY="finance-lite-v1";
const expenseDefaults=["Еда","Транспорт","Жильё","Связь","Покупки","Развлечения","Здоровье","Другое"];
const incomeDefaults=["Зарплата","Подработка","Подарок","Возврат","Другое"];
const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
const rub=n=>new Intl.NumberFormat("ru-RU",{style:"currency",currency:"RUB",maximumFractionDigits:0}).format(n||0);
const today=()=>new Date().toISOString().slice(0,10);
function demo(){const d=today();return{accounts:[{id:uid(),name:"Карта",type:"Карта",initial:35000},{id:uid(),name:"Наличные",type:"Наличные",initial:5000}],categories:{expense:[...expenseDefaults],income:[...incomeDefaults]},transactions:[]};}
let state=load(); if(!state.transactions.length){const a=state.accounts[0].id;state.transactions=[{id:uid(),type:"income",amount:68000,accountId:a,category:"Зарплата",date:today(),comment:"Аванс"},{id:uid(),type:"expense",amount:2400,accountId:a,category:"Еда",date:today(),comment:"Продукты"},{id:uid(),type:"expense",amount:900,accountId:a,category:"Транспорт",date:today(),comment:"Такси"}];save();}
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||demo()}catch{return demo()}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function accountBalance(id){const acc=state.accounts.find(a=>a.id===id);return (Number(acc?.initial)||0)+state.transactions.filter(t=>t.accountId===id).reduce((s,t)=>s+(t.type==="income"?t.amount:-t.amount),0)}
function totalBalance(){return state.accounts.reduce((s,a)=>s+accountBalance(a.id),0)}
function monthTx(){const now=new Date();return state.transactions.filter(t=>{const d=new Date(t.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()})}
function render(){document.getElementById("totalBalance").textContent=rub(totalBalance());document.getElementById("monthName").textContent=new Date().toLocaleDateString("ru-RU",{month:"long",year:"numeric"});renderStats();renderAccounts();renderTop();renderTransactions();fillSelects();}
function renderStats(){const tx=monthTx();const inc=tx.filter(t=>t.type==="income").reduce((s,t)=>s+t.amount,0);const exp=tx.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amount,0);monthIncome.textContent=rub(inc);monthExpense.textContent=rub(exp);monthResult.textContent=rub(inc-exp);monthResult.className=inc-exp>=0?"income":"expense";}
function renderAccounts(){accountsList.innerHTML="";state.accounts.forEach(a=>{const el=document.createElement("div");el.className="item";const left=document.createElement("div");left.innerHTML=`<div class="item-title"></div><small></small>`;left.querySelector(".item-title").textContent=a.name;left.querySelector("small").textContent=a.type;const right=document.createElement("div");right.className="money";right.textContent=rub(accountBalance(a.id));const del=document.createElement("button");del.className="ghost";del.textContent="×";del.onclick=()=>deleteAccount(a.id);el.append(left,right,del);accountsList.append(el)});if(!state.accounts.length)accountsList.textContent="Счетов пока нет.";}
function renderTransactions(){transactionsList.innerHTML="";[...state.transactions].sort((a,b)=>b.date.localeCompare(a.date)).forEach(t=>{const acc=state.accounts.find(a=>a.id===t.accountId);const el=document.createElement("div");el.className="item";const left=document.createElement("div");const title=document.createElement("div");title.className="item-title";title.textContent=t.category;const small=document.createElement("small");small.textContent=`${t.date} • ${acc?.name||"Счёт удалён"}${t.comment?" • "+t.comment:""}`;left.append(title,small);const sum=document.createElement("div");sum.className=t.type==="income"?"money income":"money expense";sum.textContent=(t.type==="income"?"+":"-")+rub(t.amount);const del=document.createElement("button");del.className="ghost";del.textContent="Удалить";del.onclick=()=>{state.transactions=state.transactions.filter(x=>x.id!==t.id);save();render()};el.append(left,sum,del);transactionsList.append(el)});if(!state.transactions.length)transactionsList.textContent="Операций пока нет.";}
function renderTop(){topCategories.innerHTML="";const expenses=monthTx().filter(t=>t.type==="expense");const total=expenses.reduce((s,t)=>s+t.amount,0);if(!total){topCategories.textContent="Расходов за месяц пока нет.";return}const map={};expenses.forEach(t=>map[t.category]=(map[t.category]||0)+t.amount);Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,5).forEach(([cat,sum])=>{const el=document.createElement("div");el.className="item";const wrap=document.createElement("div");wrap.style.flex="1";const line=document.createElement("div");line.className="item-title";line.textContent=`${cat} — ${rub(sum)}`;const bar=document.createElement("div");bar.className="bar";bar.innerHTML=`<i style="width:${Math.round(sum/total*100)}%"></i>`;wrap.append(line,bar);el.append(wrap);topCategories.append(el)});}
function fillSelects(){const tf=transactionForm;tf.accountId.innerHTML="";state.accounts.forEach(a=>tf.accountId.add(new Option(`${a.name} — ${rub(accountBalance(a.id))}`,a.id)));updateCategorySelect();tf.date.value=tf.date.value||today();}
function updateCategorySelect(){const type=transactionForm.type.value;transactionForm.category.innerHTML="";state.categories[type].forEach(c=>transactionForm.category.add(new Option(c,c)));}
function deleteAccount(id){if(state.transactions.some(t=>t.accountId===id)){alert("Сначала удали операции по этому счёту.");return}state.accounts=state.accounts.filter(a=>a.id!==id);save();render();}
openTransactionBtn.onclick=()=>{transactionError.textContent="";transactionForm.reset();transactionForm.date.value=today();fillSelects();transactionModal.showModal()};openAccountBtn.onclick=()=>{accountForm.reset();accountModal.showModal()};openCategoryBtn.onclick=()=>{categoryForm.reset();categoryModal.showModal()};document.querySelectorAll(".close").forEach(b=>b.onclick=()=>b.closest("dialog").close());transactionForm.type.onchange=updateCategorySelect;
transactionForm.onsubmit=e=>{e.preventDefault();const f=new FormData(transactionForm);const type=f.get("type"),accountId=f.get("accountId"),amount=Number(f.get("amount"));if(!accountId){transactionError.textContent="Создай хотя бы один счёт.";return}if(amount<=0){transactionError.textContent="Сумма должна быть больше нуля.";return}if(type==="expense"&&amount>accountBalance(accountId)){transactionError.textContent="Недостаточно денег на выбранном счёте.";return}state.transactions.push({id:uid(),type,amount,accountId,category:f.get("category"),date:f.get("date"),comment:String(f.get("comment")||"").trim()});save();transactionModal.close();render();};
accountForm.onsubmit=e=>{e.preventDefault();const f=new FormData(accountForm);state.accounts.push({id:uid(),name:String(f.get("name")).trim(),type:f.get("type"),initial:Number(f.get("initial"))||0});save();accountModal.close();render();};
categoryForm.onsubmit=e=>{e.preventDefault();const f=new FormData(categoryForm);const type=f.get("type"),name=String(f.get("name")).trim();if(name&&!state.categories[type].includes(name))state.categories[type].push(name);save();categoryModal.close();render();};
resetDemoBtn.onclick=()=>{if(confirm("Сбросить данные и вернуть демо?")){localStorage.removeItem(STORAGE_KEY);state=load();location.reload();}};
render();
